### ISSUE TITLE
Expand `readme` description

### ISSUE THREAD

**Issue by tyler36** [hanoii/ddev-ahoy#1]
Thanks for creating the addon!

I think it would be helpful to expand the readme with the following information

- what does ahoy do 
- when would you use it
- give some example of how you use

This issue is just a placeholder / suggestion. Feel free to ignore / close if you wish.

**Comment by hanoii** [comment]
@tyler36 thanks! All of that is really a copy paste from the ahoy cli homepage, which is linked. Will leave it for now and try to come up with something to add, but it's a very small cli binary :) Sometimes there's not a lot to say. I can say, however, why I like it :)

**Comment by tyler36** [comment]
Closing to tidy up.
